"""Scaffold constellation design pages under data/constellations/.

Reads hand-curated SVGs and metadata plus derived perk + lifecycle data
to regenerate browsable per-cluster pages and a top-level index. The
generated `index.html` files are idempotent — running the script twice
produces the same bytes. `current.svg` and `metadata.json` are inputs
only and are never written by this script.

Inputs:
    data/derived/perk_directory.json
    data/derived/constellation_lifecycle.json
    data/constellations/<slug>/metadata.json
    data/constellations/<slug>/current.svg

Outputs:
    data/constellations/<slug>/index.html        (14 per-cluster pages)
    data/constellations/index.html               (top-level index)
"""

from __future__ import annotations

import html
import json
import re
from collections import defaultdict
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
DATA_DERIVED = ROOT / "data" / "derived"
OUT = ROOT / "data" / "constellations"
CURRENT_FILENAME = "current.svg"
METADATA_FILENAME = "metadata.json"
INDEX_FILENAME = "index.html"
WORKBENCH_FILENAME = "tracing-workbench.html"
GENERATED_BANNER = (
    "<!-- generated by scripts/scaffold_constellation_pages.py; "
    "do not edit by hand -->"
)
FELYNE_CONSTELLATION = "Felyne Perks"


def load_json(path: Path) -> Any:
    return json.loads(path.read_text())


def escape(value: object) -> str:
    return html.escape("" if value is None else str(value), quote=True)


def cost_label(cost: int | None) -> str:
    if cost is None:
        return "?"
    if cost == 0:
        return "Free"
    return f"{cost} CP"


# --- SVG id-prefixing -------------------------------------------------------

# Match id="name", href="#name", and url(#name). We only rewrite these three
# forms — never `id_str`, `aria-labelledby`, etc.
ID_DECL_RE = re.compile(r'\bid="([A-Za-z_][A-Za-z0-9_\-:.]*)"')
HREF_RE = re.compile(r'\bhref="#([A-Za-z_][A-Za-z0-9_\-:.]*)"')
URL_REF_RE = re.compile(r'url\(#([A-Za-z_][A-Za-z0-9_\-:.]*)\)')

# Strip out any leading <?xml ?> prolog so we can inline the SVG safely.
XML_PROLOG_RE = re.compile(r'^\s*<\?xml[^?]*\?>\s*', re.DOTALL)


def prefix_svg_ids(svg_text: str, prefix: str) -> str:
    """Rewrite id, href=#…, and url(#…) so ids are unique on the page.

    `prefix` is appended in front of every existing id, separated by `-`.
    """
    svg_text = XML_PROLOG_RE.sub("", svg_text)

    def _decl(match: re.Match[str]) -> str:
        return f'id="{prefix}-{match.group(1)}"'

    def _href(match: re.Match[str]) -> str:
        return f'href="#{prefix}-{match.group(1)}"'

    def _url(match: re.Match[str]) -> str:
        return f'url(#{prefix}-{match.group(1)})'

    out = ID_DECL_RE.sub(_decl, svg_text)
    out = HREF_RE.sub(_href, out)
    out = URL_REF_RE.sub(_url, out)
    return out.strip()


# --- Data assembly ----------------------------------------------------------


def load_lifecycle() -> list[dict[str, Any]]:
    data = load_json(DATA_DERIVED / "constellation_lifecycle.json")
    return list(data["constellations"])


def load_perks() -> list[dict[str, Any]]:
    data = load_json(DATA_DERIVED / "perk_directory.json")
    return [p for p in data["perks"] if p.get("constellation") != FELYNE_CONSTELLATION]


def jumps_for(constellation: str, perks: list[dict[str, Any]]) -> list[dict[str, Any]]:
    """Return jumps in this constellation, sorted by perk count desc then name."""
    grouped: dict[str, list[dict[str, Any]]] = defaultdict(list)
    for perk in perks:
        if perk.get("constellation") != constellation:
            continue
        grouped[perk["jump"]].append(perk)
    return sorted(
        ({"name": jump, "perks": items} for jump, items in grouped.items()),
        key=lambda j: (-len(j["perks"]), j["name"]),
    )


def perks_for(constellation: str, perks: list[dict[str, Any]]) -> list[dict[str, Any]]:
    """All perks in the constellation, sorted by jump (alpha) then cost desc."""
    in_const = [p for p in perks if p.get("constellation") == constellation]

    def cost_sort_key(p: dict[str, Any]) -> int:
        cost = p.get("cost")
        # None sorts last (lowest) within a jump group
        return -1 if cost is None else cost

    return sorted(
        in_const,
        key=lambda p: (p.get("jump") or "", -cost_sort_key(p), p.get("name") or ""),
    )


def status_string(lifecycle: dict[str, Any]) -> str:
    revealed = lifecycle.get("revealed_at_chapter")
    completed = lifecycle.get("completed_at_chapter")
    parts = []
    if revealed:
        parts.append(f"revealed ch {revealed}")
    if completed:
        parts.append(f"completed ch {completed}")
    else:
        parts.append("incomplete")
    return " · ".join(parts)


# --- HTML rendering ---------------------------------------------------------

PAGE_CSS = """  :root {
    --void:       #03080d;
    --void-soft:  #07121a;
    --ink:        #e8fdff;
    --muted:      #9ad7df;
    --dim:        #5f9ba4;
    --cyan:       #5cf4ff;
    --edge-soft:  rgba(92, 244, 255, 0.22);
    --serif:      Georgia, "Times New Roman", serif;
    --sans:       "Avenir Next", "Segoe UI", system-ui, sans-serif;
    --mono:       ui-monospace, SFMono-Regular, Menlo, monospace;
  }
  html, body { margin: 0; padding: 0; background: var(--void); color: var(--ink);
               font-family: var(--sans); }
  body { padding: 28px 36px 48px; min-height: 100vh; }
  h1 { font-family: var(--serif); font-size: 28px; color: var(--cyan);
       margin: 0 0 6px 0; letter-spacing: 0.03em; }
  h2 { font-family: var(--serif); font-size: 20px; color: var(--cyan);
       margin: 30px 0 12px 0; }
  .back-link, .workbench-link { display: inline-block; margin: 0 14px 18px 0;
                                font-family: var(--mono); font-size: 12px;
                                color: var(--dim); }
  .workbench-link { color: var(--cyan); }
  dl.meta { margin: 0 0 22px 0; font-family: var(--mono); font-size: 12px;
            display: grid; grid-template-columns: 200px 1fr; row-gap: 4px;
            column-gap: 14px; max-width: 760px; }
  dl.meta dt { color: var(--dim); text-transform: uppercase; letter-spacing: 0.08em; }
  dl.meta dd { margin: 0; color: var(--ink); }
  p.shape-concept { font-family: var(--serif); font-style: italic; color: var(--muted);
                    font-size: 15px; max-width: 60ch; margin: 0 0 24px 0; line-height: 1.4; }
  p.shape-concept .label { display: block; font-family: var(--mono); font-style: normal;
                           color: var(--dim); text-transform: uppercase; letter-spacing: 0.08em;
                           font-size: 11px; margin-bottom: 4px; }
  .current-svg { width: min(420px, 100%); aspect-ratio: 1 / 1;
                 border: 1px solid var(--edge-soft); border-radius: 4px;
                 background: var(--void-soft); margin: 0 0 28px 0; display: block; }
  .current-svg svg { width: 100%; height: 100%; display: block; }
  table { border-collapse: collapse; width: min(100%, 980px); margin: 0 0 22px 0;
          font-size: 13px; }
  th, td { border: 1px solid var(--edge-soft); padding: 7px 10px; vertical-align: top; }
  th { color: var(--cyan); font-family: var(--mono); font-size: 11px; font-weight: 600;
       text-align: left; text-transform: uppercase; letter-spacing: 0.08em;
       background: rgba(92, 244, 255, 0.06); }
  td { color: var(--ink); line-height: 1.35; }
  td.num { font-family: var(--mono); color: var(--muted); text-align: right; width: 80px; }
  td.cost { font-family: var(--mono); color: var(--muted); width: 100px; }
  td.jump { color: var(--muted); }
  a { color: var(--cyan); text-decoration-color: var(--edge-soft); }
"""

INDEX_CSS = """  :root {
    --void:       #03080d;
    --void-soft:  #07121a;
    --ink:        #e8fdff;
    --muted:      #9ad7df;
    --dim:        #5f9ba4;
    --cyan:       #5cf4ff;
    --edge-soft:  rgba(92, 244, 255, 0.22);
    --serif:      Georgia, "Times New Roman", serif;
    --sans:       "Avenir Next", "Segoe UI", system-ui, sans-serif;
    --mono:       ui-monospace, SFMono-Regular, Menlo, monospace;
  }
  html, body { margin: 0; padding: 0; background: var(--void); color: var(--ink);
               font-family: var(--sans); }
  body { padding: 28px 36px 48px; min-height: 100vh; }
  h1 { font-family: var(--serif); font-size: 28px; color: var(--cyan);
       margin: 0 0 14px 0; letter-spacing: 0.03em; }
  p.lede { color: var(--muted); margin: 0 0 22px 0; max-width: 68ch; line-height: 1.45; }
  table { border-collapse: collapse; width: min(100%, 1180px); font-size: 13px; }
  th, td { border: 1px solid var(--edge-soft); padding: 8px 10px; vertical-align: middle; }
  th { color: var(--cyan); font-family: var(--mono); font-size: 11px; font-weight: 600;
       text-align: left; text-transform: uppercase; letter-spacing: 0.08em;
       background: rgba(92, 244, 255, 0.06); }
  td.num { color: var(--dim); font-family: var(--mono); text-align: right; width: 70px; }
  td.name { min-width: 200px; }
  td.status { font-family: var(--mono); color: var(--muted); font-size: 12px; }
  td.actions { font-family: var(--mono); font-size: 12px; white-space: nowrap; }
  td.actions a + a { margin-left: 12px; }
  .thumb-cell { width: 112px; text-align: center; padding: 6px; }
  .thumb { width: 96px; height: 96px; display: inline-block;
           border: 1px solid var(--edge-soft); border-radius: 4px;
           background: var(--void-soft); padding: 4px; box-sizing: border-box; }
  .thumb svg { width: 100%; height: 100%; display: block; }
  a { color: var(--cyan); text-decoration-color: var(--edge-soft); }
"""


def render_jumps_table(jumps: list[dict[str, Any]]) -> str:
    if not jumps:
        return '  <p class="empty">No jumps for this constellation.</p>'
    rows = []
    for jump in jumps:
        rows.append(
            "    <tr>"
            f"<td>{escape(jump['name'])}</td>"
            f"<td class=\"num\">{len(jump['perks'])}</td>"
            "</tr>"
        )
    return (
        "  <table>\n"
        "    <thead><tr><th>Jump</th><th>Perks</th></tr></thead>\n"
        "    <tbody>\n"
        + "\n".join(rows)
        + "\n    </tbody>\n"
        "  </table>"
    )


def render_perks_table(perks: list[dict[str, Any]]) -> str:
    if not perks:
        return '  <p class="empty">No perks for this constellation.</p>'
    rows = []
    for perk in perks:
        rows.append(
            "    <tr>"
            f"<td class=\"jump\">{escape(perk.get('jump'))}</td>"
            f"<td>{escape(perk.get('name'))}</td>"
            f"<td class=\"cost\">{escape(cost_label(perk.get('cost')))}</td>"
            "</tr>"
        )
    return (
        "  <table>\n"
        "    <thead><tr><th>Jump</th><th>Perk</th><th>Cost</th></tr></thead>\n"
        "    <tbody>\n"
        + "\n".join(rows)
        + "\n    </tbody>\n"
        "  </table>"
    )


def render_cluster_page(
    cluster: dict[str, Any],
    metadata: dict[str, Any],
    svg_inline: str,
    jumps: list[dict[str, Any]],
    perks: list[dict[str, Any]],
) -> str:
    name = cluster["name"]
    slug = cluster["slug"]
    slot = cluster["slot_position"]
    intended_image = metadata.get("intended_image", "")
    perk_count = len(perks)
    jump_count = len(jumps)

    meta_dl = (
        '  <dl class="meta">\n'
        f'    <dt>Slot</dt><dd>{slot:02d}</dd>\n'
        f'    <dt>Slug</dt><dd>{escape(slug)}</dd>\n'
        f'    <dt>Jumps</dt><dd>{jump_count}</dd>\n'
        f'    <dt>Perks</dt><dd>{perk_count}</dd>\n'
        f'    <dt>Revealed at chapter</dt><dd>{escape(cluster.get("revealed_at_chapter") or "—")}</dd>\n'
        f'    <dt>Completed at chapter</dt><dd>{escape(cluster.get("completed_at_chapter") or "incomplete")}</dd>\n'
        f'    <dt>Entered pool at chapter</dt><dd>{escape(cluster.get("entered_pool_at_chapter") or "—")}</dd>\n'
        '  </dl>'
    )

    workbench_href = f"../{WORKBENCH_FILENAME}?constellation={slug}"

    return (
        "<!DOCTYPE html>\n"
        f"{GENERATED_BANNER}\n"
        '<html lang="en">\n'
        "<head>\n"
        '<meta charset="utf-8"/>\n'
        f"<title>{escape(name)} · Constellation</title>\n"
        "<style>\n"
        f"{PAGE_CSS}"
        "</style>\n"
        "</head>\n"
        "<body>\n"
        f'<h1>{slot:02d} · {escape(name)}</h1>\n'
        '<a class="back-link" href="../index.html">← Constellation index</a>\n'
        f'<a class="workbench-link" href="{escape(workbench_href)}">Edit in workbench →</a>\n'
        f"{meta_dl}\n"
        '<p class="shape-concept">'
        '<span class="label">Intended image</span>'
        f"{escape(intended_image)}</p>\n"
        '<div class="current-svg">\n'
        f"{svg_inline}\n"
        "</div>\n"
        "<h2>Jumps</h2>\n"
        f"{render_jumps_table(jumps)}\n"
        "<h2>Perks</h2>\n"
        f"{render_perks_table(perks)}\n"
        "</body>\n"
        "</html>\n"
    )


def render_top_index(records: list[dict[str, Any]]) -> str:
    rows = []
    for rec in records:
        cluster = rec["cluster"]
        slug = cluster["slug"]
        name = cluster["name"]
        slot = cluster["slot_position"]
        per_page = f"{escape(slug)}/index.html"
        workbench = f"{WORKBENCH_FILENAME}?constellation={slug}"
        rows.append(
            "    <tr>"
            f"<td class=\"num\">{slot:02d}</td>"
            f"<td class=\"name\"><a href=\"{escape(per_page)}\">{escape(name)}</a></td>"
            f"<td class=\"thumb-cell\"><span class=\"thumb\">{rec['svg_inline']}</span></td>"
            f"<td class=\"num\">{rec['jump_count']}</td>"
            f"<td class=\"num\">{rec['perk_count']}</td>"
            f"<td class=\"status\">{escape(status_string(cluster))}</td>"
            "<td class=\"actions\">"
            f"<a href=\"{escape(per_page)}\">Details</a>"
            f"<a href=\"{escape(workbench)}\">Edit</a>"
            "</td>"
            "</tr>"
        )
    rows_html = "\n".join(rows)
    return (
        "<!DOCTYPE html>\n"
        f"{GENERATED_BANNER}\n"
        '<html lang="en">\n'
        "<head>\n"
        '<meta charset="utf-8"/>\n'
        "<title>Constellation index</title>\n"
        "<style>\n"
        f"{INDEX_CSS}"
        "</style>\n"
        "</head>\n"
        "<body>\n"
        "<h1>Constellation index</h1>\n"
        '<p class="lede">All 14 cluster constellations in slot order. '
        "Click <em>Details</em> for the per-cluster page, or "
        "<em>Edit</em> to open the tracing workbench preloaded with that "
        "constellation.</p>\n"
        "<table>\n"
        "  <thead>\n"
        "    <tr>"
        "<th>Slot</th><th>Name</th><th>Current</th>"
        "<th>Jumps</th><th>Perks</th><th>Status</th><th>Actions</th>"
        "</tr>\n"
        "  </thead>\n"
        "  <tbody>\n"
        f"{rows_html}\n"
        "  </tbody>\n"
        "</table>\n"
        "</body>\n"
        "</html>\n"
    )


# --- Main -------------------------------------------------------------------


def main() -> None:
    lifecycle = load_lifecycle()
    perks = load_perks()
    # Preserve the slot_position order from lifecycle (already 1..14).
    clusters = sorted(lifecycle, key=lambda c: c["slot_position"])

    records: list[dict[str, Any]] = []
    for cluster in clusters:
        slug = cluster["slug"]
        folder = OUT / slug
        if not folder.exists():
            raise SystemExit(f"missing constellation folder: {folder}")
        metadata_path = folder / METADATA_FILENAME
        svg_path = folder / CURRENT_FILENAME
        metadata = load_json(metadata_path)
        svg_text = svg_path.read_text()

        cluster_jumps = jumps_for(cluster["name"], perks)
        cluster_perks = perks_for(cluster["name"], perks)

        svg_inline = prefix_svg_ids(svg_text, slug)
        page_html = render_cluster_page(
            cluster=cluster,
            metadata=metadata,
            svg_inline=svg_inline,
            jumps=cluster_jumps,
            perks=cluster_perks,
        )
        (folder / INDEX_FILENAME).write_text(page_html)

        records.append(
            {
                "cluster": cluster,
                "svg_inline": svg_inline,
                "jump_count": len(cluster_jumps),
                "perk_count": len(cluster_perks),
            }
        )

    (OUT / INDEX_FILENAME).write_text(render_top_index(records))

    print(f"Wrote {len(records)} per-cluster pages + 1 top-level index under {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
